### PR TITLE
update keyboard_visibility to latest version and fix bugs after that

### PR DESCRIPTION
**Pull request by alphamikle**
After updating kv to latest version api was changed and typeahead was updated too

### CODE REVIEW

**Comment by sjmcdowall** [comment]
@alphamikle  -- I Merged another PR that updated the version.  Can you check and re-submit against that version?

**Comment by alphamikle** [comment]
@sjmcdowall all done

**Comment by bytespryte** [comment]
Thanks for the update @alphamikle 
@sjmcdowall Can we get a merge here, my man? 🙏

**Comment by sjmcdowall** [comment]
Done!  1.8.3 published ..

**Comment by bytespryte** [comment]
Much appreciated @sjmcdowall !!!

**Pull request merged**
