### PR TITLE
feature: add scrollbarAlwaysVisible argument

### LINKED ISSUE #499: How can I make the scrollbar always visible?
How can I make the scrollbar always visible?

### PR DESCRIPTION
**Pull request by eivihnd**
By setting scrollbarAlwaysVisible the scrollbar will not fade away while not scrolling, thus helping the user to understand that more content is available. 

Resolves #499

### CODE REVIEW

**Comment by sjmcdowall** [comment]
The code looks fine -- but could you add 2 test cases (one for the default false and then one set to true) -- and update the README documentation describing the new feature?? 

Thanks!

**Comment by eivihnd** [comment]
Thanks for the feedback. I will gladly add the test cases and documentation. However, I am not experienced in widget testing, would you be able to give me a hint to lead me in the right direction?

**Comment by sjmcdowall** [comment]
Actually I am a little rusty too -- but we have 16 (?) current tests so I would think one of them could be used as a template for this one?

**Comment by eivihnd** [comment]
Did a refactor of my initial solution, and moved it to the SuggestionsBoxDecoration.
Added tests and updated readme. Had to give the Cupertino implementation some love as the scroll controller was not added to the Cupertino suggestion list view and scroll bar.

**Comment by sjmcdowall** [comment]
Closed as part of PR 512

**Pull request closed without merging**
