### PR TITLE
Feat/key up down

### LINKED ISSUE #402: unable to use up and arrow key in keyboard for selecting suggestions

### PR DESCRIPTION
**Pull request by Pierre-Monier**
close #402 

- add key up/down support to select suggestion
- write test for this feature
- add web platform for example app

I havn't touch the CupertinoFlutterTypeahead part, if the logic is validated I will also integrate it for the CupertinoFlutterTypeahead  widget.

### CODE REVIEW

**Comment by sjmcdowall** [comment]
Can you fix the merge conflicts that are now here?  Then I will merge in.  Thanks.

**Comment by sjmcdowall** [comment]
@Pierre-Monier -- Will you be able to get to this soon?  I'd like to merge and push this key feature.

**Comment by Pierre-Monier** [comment]
Yeah, I will do this tomorrow

**Comment by sjmcdowall** [comment]
Great! Thanks @Pierre-Monier !!

**Comment by Pierre-Monier** [comment]
I fixed merge conflicts

**Pull request merged**
