### PR TITLE
Bug fixes, some related to null safety

### PR DESCRIPTION
**Pull request by miDeb**
There are three commits in this pull request:
- One adds some very basic tests (there should definitely be more tests though)
- The second one fixes the bugs uncovered by the tests from the first commit
- Last but not least, I recreated the example project and migrated it to null safety

### CODE REVIEW

**Comment by mzdm** [comment]
I have tried this and works like a charm.

@sjmcdowall can we can this merged? 🙏 The current version has a lot of issues.

@miDeb maybe remove some unnecessary examples (like Linux build, ..) so it is easier to review?

**Review by mzdm — APPROVED** [review]

**Comment by miDeb** [comment]
> maybe remove some unnecessary examples (like Linux build, ..) so it is easier to review?

If the mantainer finds this unnecessary I am happy to remove it. They are however just the files that are generated by `flutter create`, so a close review should not be needed. Why do you think that they are unnecessary?

If the recreation of the example project is unwanted it should be possible to only take the first two commits.

**Comment by mzdm** [comment]
Ye but IIRC these are generated only if you have `flutter config --enable-linux-desktop` enabled and considering that on pub.dev is not desktop and web listed it might be misleading to some people (if the package really does not work on these platforms - I didn't try and sometimes pub.dev shows it wrong). But it's just an example folder so it does not matter...

**Comment by miDeb** [comment]
I'm on linux (as you may have guessed) and it works. I don't know why pub doesn't show desktop support, maybe because of the dependency on keyboard_visibility (which doesn't support desktop)?

**Pull request merged**
