### PR TITLE
Support `autofillHints` properties

### PR DESCRIPTION
**Pull request by dab246**

### CODE REVIEW

**Comment by sjmcdowall** [comment]
This looks ok -- but I would like to see a test case added that uses it as well as an example of its usage... Thanks

**Comment by dab246** [comment]
> This looks ok -- but I would like to see a test case added that uses it as well as an example of its usage... Thanks

Thanks. You can see a specific example, how to configure to use autofill in our PR. https://github.com/linagora/tmail-flutter/pull/1505

**Comment by dab246** [comment]
@sjmcdowall  Please review help me. Thanks

**Comment by dab246** [comment]
@sjmcdowall I am still waiting for your response.

**Comment by sjmcdowall** [comment]
Hi! So this looks good but sadly now has merge conflicts that needs to be resolved once I push the other PRs ...

**Comment by sumitsharansatsangi** [comment]
@sjmcdowall , Please close this PR.

**Pull request closed without merging**
