### PR TITLE
Reduce excessive calls of suggestionsCallback

### PR DESCRIPTION
**Pull request by darkstarx**
Fixes overlay blinking (double unfolding) on get focus of text field.
1. in `suggestionsCallback` call `setState`
2. write something in text field and select any suggestion
3. the widget focus will be lost, `setState` will be called, and the widget will rebuild
4. tap on the text field
5. you'll see the overlay unfolds twice (first from `didChangeDependencies` and then from `didUpdateWidget`, and `_activeCallbackIdentity` guard will not help you).

### CODE REVIEW

**Comment by sjmcdowall** [comment]
LGTM -- I will merge. Thanks!

**Comment by Max-Might** [comment]
Is this version published on pub.dev? I do not see it there.

**Comment by sjmcdowall** [comment]
How embarrassing -- it is now published :)

**Comment by Max-Might** [comment]
All good. Thanks @sjmcdowall  :)

**Pull request merged**
