### PR TITLE
Change the contribution section of README

### PR DESCRIPTION
**Pull request by AbdulRahmanAlHamali**
* Highlight the team members
* Thank the contributors
* Refer to contribution guidelines

### CODE REVIEW

**Comment by AbdulRahmanAlHamali** [comment]
On another note, @sjmcdowall, @KaYBlitZ are you guys looking for another project to contribute to? :laughing:

**Comment by AbdulRahmanAlHamali** [comment]
[Flutter Pagewise](https://github.com/AbdulRahmanAlHamali/flutter_pagewise)
It is a cool little project for paginated ListView and GridView.

It needs some serious polishing, but I don't have the time on my hand to do much. Are you guys interested?

**Comment by KaYBlitZ** [comment]
Seems like a cool project. Definitely interested in helping out.

**Comment by AbdulRahmanAlHamali** [comment]
Alright I have added you both as collaborators to the project. Feel free to look around the code, issues, etc.

There are 10 open issues right now, some are very trivial to solve, and some require some hard work. If you want I can start assigning to you some of the more trivial ones to familiarize yourself with the project. What do you guys think?

BTW, I really appreciate the hard work you are putting into this. In the past period I moved from Lebanon to Canada, and moved from a frontend developer, to a DevOps tooling developer. I am in another world right now, very far from Flutter and the likes :laughing: which is why I am having a lot of trouble maintaining those projects. So again, I really appreciate everything you've been doing!

**Comment by sjmcdowall** [comment]
Wow -- that is QUITE a change!  Where in Canada?  Especially now I would think the weather would be quite different between Front-End and Dev Ops!   As well as Lebanon to Canada! :) 

As soon as I get the other Issue/PR done on TypeAhead I'll jump on some of the trivial stuff -- as well as adding the linter package, etc. if not already done.  I like the Flutter Dart Linter rules -- sort of strict but not horrible .

**Comment by AbdulRahmanAlHamali** [comment]
Yeah it is a huge change! I am in Quebec right now, temperature is -18 outside, while in Beirut (Lebanon) it's 17!
And yeah, it is quite different between UI and DevOps, but I seem to enjoy the latter more :)

**Comment by AbdulRahmanAlHamali** [comment]
No problem, take your time and good luck!

**Comment by AbdulRahmanAlHamali** [comment]
Alright I was able to save the situation for now in Pagewise; I pushed a new version that solves almost all the problems that people have been complaining about. but I will still need your help for future versions! :smile:

**Comment by sjmcdowall** [comment]
Hey no worries! I saw all the commits! Nice

**Comment by KaYBlitZ** [comment]
Great job! Looks like everything is pretty much solved.

**Pull request merged**
