### PR TITLE
Opt into the null safety

### PR DESCRIPTION
**Pull request by glynskyi**

### CODE REVIEW

**Comment by DevNico** [comment]
@AbdulRahmanAlHamali Any timeline on when this will be reviewed / merged?

**Comment by sjmcdowall** [comment]
@glynskyi -- So how do people get the new SDK requrired? I just updated Flutter and the Dart SDK is still at 2.10.5 not the required 2.12 ...

**Comment by DevNico** [comment]
You need to use the dev channel of flutter beta should work too but I'm not sure about it.

**Comment by sjmcdowall** [comment]
Well the PR is pushed to master so it's available -- but I am hestiatant to push this to dev pub until stable release is at the proper SDK .. I don't want people to have to use DEV flutter for their projects

**Comment by DevNico** [comment]
You could release a pre-release version as described in the null safety migration guide: https://dart.dev/null-safety/migration-guide#package-version. The pre-release is an opt in kind of release.

**Comment by featzima** [comment]
@sjmcdowall we have a lot of projects which are designed for the desktop platforms. That's why we use the dev Flutter branch. Please publish the master branch to the pud.dev and it will be published as a null-safety version next to a stable version. For instance you can see how it works in the Bloc library https://pub.dev/packages/bloc (Latest: 6.1.1 / Prerelease: 7.0.0-nullsafety.1)

**Comment by sjmcdowall** [comment]
OK - -let me research how to do this by looking at the example -- never did a pre-lease thing before.

**Comment by miDeb** [comment]
Hi @sjmcdowall, do you plan on releasing a null safe version soon? The null safe versions of packages are usually released as a pre-release (that means that people will still use the old version by default, but can choose to use the newer one). Pre-releases are indicated with a dash, in this case that would be `3.0.0-nullsafety.0`. For that you would only have to update the version in pubspec.yaml to `3.0.0-nullsafety.0` and push it to pub. Pub will automatically detect that it is a prerelease.

>  Most people do ^2.X so this would break that

It wouldn't _actually_ break it, because pub [always prefers stable versions over pre-releases](https://dart.dev/tools/pub/publishing#publishing-prereleases), so as long as it is only a pre-release we would be safe. But since this is a breaking change, a new major version is definitely appropriate.

**Comment by sjmcdowall** [comment]
Oh! Good to know about how pub handles pre-releases.  I was just waiting until someone confirmed the approach of  3.0.0-nullsafety.0 is the right approach. Sounds like it is -- so I will go ahead and do the change and push "soon" (today sometime)

**Comment by sjmcdowall** [comment]
OK -- Published -- let me know how it goes

**Comment by miDeb** [comment]
Everything looking good, thanks!

**Pull request merged**
