### PR TITLE
SuggestionBox can be on top of TextField.

### PR DESCRIPTION
**Pull request by Rassell**
- Finish conflicts from:
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/10

- Added noResize flag in order to put suggestions on top (or opposite direction) if items collapse with the keyboard
- If the list is on top change order of suggestion to have close the first ones

### CODE REVIEW

**Comment by AbdulRahmanAlHamali** [comment]
Thank you for your contribution @Rassell , it is highly appreciated by  everyone using this package and me!

I will review your contribution within a few days and hopefully merge it. But I have to ask, why are there many changes that don't seem relevant to the pull request?

**Comment by Rassell** [comment]
Well, it's about when the suggestions are wanted to be shown but there is no space between them and the keyboard shown them on top.

**Comment by AbdulRahmanAlHamali** [comment]
I understand, and it is definitely a good idea. But looking at the commit, there are many things changed that are not related to the actual change that you made, which is not helping when trying to understand the detail of your pull request.

It is better to push a commit that changes only the parts immediately related to your change, otherwise it will be hard to review, and will make things harder to manage in the future.

Thank you again!

**Comment by KaYBlitZ** [comment]
Added in #28

**Pull request closed without merging**
