### PR TITLE
autofillHints for TextFieldConfiguration

### PR DESCRIPTION
**Pull request by SimonIT**
I would like to set the autofillHints for the text fields

### CODE REVIEW

**Comment by sjmcdowall** [comment]
@SimonIT -- have you tried the new Flutter 2 widget that does this similar / same behavior? Just curious

**Comment by SimonIT** [comment]
You mean [Autocomplete](https://api.flutter.dev/flutter/material/Autocomplete-class.html) and [RawAutocomplete](https://api.flutter.dev/flutter/widgets/RawAutocomplete-class.html)?
Yes I looked at them (because I saw #293) but then decided, that they are not very flexible. There are no options to set the input type etc.. This is very important to us because the customer wants an accessibility friendly app with good support for screen readers.
I also recognized that it also only possible to set the values via `optionsBuilder`. The problem is, that I get my autocomplete values via an api endpoint. This makes it a bit complicated to get the data in as they are asynchronously fetched and the builder doesn't allow Future's.
That's why I choose this lib

**Comment by mr-oggy** [comment]
facing flickering issue in autofill hints

**Comment by mr-oggy** [comment]
https://user-images.githubusercontent.com/53708183/174007377-093229b3-f3fa-490d-9dd3-0be9ef0271ce.mp4

**Pull request merged**
