### PR TITLE
Support for platforms not supported by KeyboardVisibility

### PR DESCRIPTION
**Pull request by ReniDelonzek**
I noticed that the only thing limiting the use of this library on the desktop is the fact that KeyboardVisibility doesn't support desktop, so I added a simple conditional that checks if it's platform compatible before making use of the lib.

There may be other points that this library doesn't support on the desktop that I'm ignoring, please let me know if that's the case

### CODE REVIEW

**Comment by sjmcdowall** [comment]
THis has a conflict and Iam not sure its needed as I think someone else added this logic?

**Comment by ReniDelonzek** [comment]
When I submitted this PR, the feature had not yet been implemented. If it has already been done, we can close the PR

**Comment by clragon** [comment]
#333 was merged to fix this

**Comment by clragon** [comment]
on that note, this PR also changes the `Flutter_export_evironment.sh` file, which should not be checked it.
we should probably add this file to the gitignore and then delete it.

**Pull request closed without merging**
