### PR TITLE
add itemSeparatorBuilder

### PR DESCRIPTION
**Pull request by altynbek132**
#316

### CODE REVIEW

**Comment by sjmcdowall** [comment]
Can you add a test to the test suite?

**Comment by sjmcdowall** [comment]
This PR now has a Merge Conflict -- as well as still needed an example showing the usage and a test case (or more) ...

**Comment by sjmcdowall** [comment]
Still has a merge conflict ...

**Comment by sumitsharansatsangi** [comment]
@sjmcdowall , Please close this PR.

**Comment by sjmcdowall** [comment]
Closing as per Sumit K.

**Pull request closed without merging**
