### PR TITLE
add autoFlipAxis feature

### PR DESCRIPTION
**Pull request by zacwolfe**
Fix for https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/79

If autoFlipAxis is set to true, in the case where the suggestions box has less than MIN_OVERLAY_SPACE to grow in the desired direction, the direction axis will be temporarily flipped if there's more room available in the opposite direction.  Defaults to false

### CODE REVIEW

**Comment by KaYBlitZ** [comment]
Functionality is great! I submitted a PR in your branch for some stuff I found. I think renaming it to autoFlipDirection will make it easier to understand and find, since we already have a property named direction.

**Comment by zacwolfe** [comment]
Yes, I like that better!

fat-fingered on tiny keyboard

**Comment by sjmcdowall** [comment]
@KaYBlitZ -- you going to merge to master and pub ??

**Comment by KaYBlitZ** [comment]
I was going to, but do you want to do it? I don't want to publish to pub while you're trying to. Might cause errors.

**Comment by sjmcdowall** [comment]
Yeah i'll do the pub -- hold on ;)

**Pull request merged**
