### PR TITLE
refactor: all code

### PR DESCRIPTION
**Pull request by clragon**
## Info

This is a large scale breaking refactor of the library that seeks to unify all code that can be shared between platforms.
This change can help with library maintenance as it will be much easier for contributors to add new features safely and connect them in the different platforms. It will also prevent the iOS implementation from being left behind, as it is currently the case.

The PR is a breaking change, so it needs a **major version increase** on release.
Please do not merge the PR while in draft.

## Guidelines

The current `Changelog.md` format is inconsistent and out of shape.
To rectify this, I have applied the [keep-a-changelog](https://keepachangelog.com/en/1.0.0/) format.

The format is now consistent.
Please write future Changelog entries in this format as well.

You can simplify this process by using a tool called [cider](https://pub.dev/packages/cider).
You can install cider with `pub global activate cider`.
You can add a new entry with `cider log <type> '<message>'`.
You can even adjust the version in the pubspec yml automatically with: `cider bump <part>`.
See the package readme for further details.

It would also be nice if all commit messages followed [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

## Changes

Notable changes in this PR that apply to users of the package are added to the Changelog.
Other changes are listed here:

- enforced lint and style 
  code is now more consistent.
- completely rewrote `Overlay` interactions
  now uses OverlayPortal as well as all-internal size and position updating mechanism, called "Floater".
  this also fixes various issues, like being unable to tap suggestions and needing to manually resize for dialogs/animations.
- rewrote the SuggestionsBox object completely
  it is now a Widget that composes different other widgets
- split functionality in many different widgets
  which can be injected and tested on their own, reducing overall complexity.
- rewrote SuggestionsController
  now actually holds the suggestions and their state as well as the open/close and focus state. also notifies.
- removed Text Field Config and replaced it with a builder.
- removed Decoration Config and replaced it with a builder.
- removed Form Field variants, as the builder can be used for that.
- updated and unified cupertino
  now uses much of the same code as material and cannot be left behind so easily.
- fixed animations
  they do no longer restart after each search. additionally, size changes are now animated.
- rewrote all tests
  tests now target the specific components for functionalities instead of the root widget alone.
- completely rewrote example
  now a single basic example that can be configured live to show off capabilities
- removed example platform folders
  these only add unnecessary code that will become outdated. users can regenerate them for themselves.
- updated example readme
  includes how to generate the platform folders
- updated contribution guidelines
  to include all standards like: semver, conventional commits, keep-a-changelog.
- removed the scripts folder
  as all scripts were trivial commands or outdated.

### CODE REVIEW

**Comment by clragon** [comment]
Notes (for myself):

- [ ] the change might be possible non-breaking, if we define a deprecated typedef for the cupertino suggestion box controller
- [ ] figure out where those Material widgets went missing in the suggestions box for Material

**Comment by sjmcdowall** [comment]
Let me know when it's ready to rock .. are there other PRs in the list that you deem ready?

**Comment by clragon** [comment]
right now this PR will probably break all other PRs most definitely.
So I'll focus on getting this ready for now, so they dont stack up. 

Since we just merged the loading more, that will need to be incorporated here too.

**Comment by sjmcdowall** [comment]
Hey there @clragon -- It appears (and I want to confirm) that this PR isn't ready yet .. and I should wait on all PRs until this is done??

**Comment by clragon** [comment]
@sjmcdowall 
PRs  #530 and #531
should be good to merge. 
please hold on with merging any other PRs as I otherwise have to rebase this breaking branch to incorporate them.

**Comment by clragon** [comment]
@sjmcdowall 

The current `Changelog.md` format is inconsistent and out of shape.
To rectify this, I have applied the [keep-a-changelog](https://keepachangelog.com/en/1.0.0/) format.

The format is now consistent.
Please write future Changelog entries in this format as well.

You can simplify this process by using a tool called [cider](https://pub.dev/packages/cider).
You can install cider with `pub global activate cider`.
You can add a new entry with `cider log <type> '<message>'`.
You can even adjust the version in the pubspec yml automatically with: `cider bump <part>`.
See the package readme for further details.

**Comment by clragon** [comment]
@sjmcdowall I have reverted the merge of #519 in this branch because it would be conflicting.
We will have to write that code again later. on my fork is the old branch with these changes which we can use as a base.

**Comment by sjmcdowall** [comment]
Okay -- I see this is still in Draft mode .. Just let me know when and .. actually .. how you want me to merge this .. :)

**Comment by clragon** [comment]
note to myself:

- [ ] switching themes with the suggestions box open does not update the colors of the suggestion list

**Comment by clragon** [comment]
fix #527

**Comment by sjmcdowall** [comment]
Hey there @clragon -- just wondering if you have any ETA when all these big changes will be complete and ready to merge into the master and deployed as a new major update?  I'll probably also need help figuring out exactly HOW to cleanly merge this quantity of changes in .. :)

**Comment by clragon** [comment]
Hi @sjmcdowall,
I am just about finished. The last item in the checklist is the last thing I will be doing for this PR.
I might be able to do this today or might take a couple more days.
Its a bug in how we move the focus over the suggestions list when using the keyboard. Once thats fixed, everything is done. 

The PR can be merged via `Rebase and Merge`. We want to retain the commit history for this one because a lot of the changes I have made would otherwise become harder to understand. 

image

Once the PR is merged, you can follow the updated Contribution markdown file. If you need help with that feel free to ask me.
I have already written all the Changelog entries for the new Unreleased version. There is also a migration guide in the Readme now.

If you would like to help otherwise, you could test the new Example. 
Feedback on its quality would be great and any bugs you spot are of course also welcome. 
It would also be great if we had a new GIF for the readme that shows off the packages features.

**Comment by clragon** [comment]
@sjmcdowall 
I believe I am done. The PR is now in a state where it can be merged and released.

**Comment by sjmcdowall** [comment]
Major re-write my our new hero @clragon !  This will be a major version change upgrade just to be safe.

**Pull request merged**
