### PR TITLE
file-strucrture

### PR DESCRIPTION
**Pull request by vasilich6107**
Fix for #324

### CODE REVIEW

**Comment by sjmcdowall** [comment]
Hey @vasilich6107 -- can you update the PR -- I merged another fix in and that made this conflict .  Should be easy enough I think -- just grab the newest flutter_typeahead.dart and then re-move it to where you had it?

**Comment by vasilich6107** [comment]
@sjmcdowall done

**Comment by sjmcdowall** [comment]
Merged and published -- thanks

**Comment by vasilich6107** [comment]
Thanks for immediate release! ;-)

**Pull request merged**
