### PR TITLE
#459 returned visibility to classes that are not in the example

### PR DESCRIPTION
**Pull request by ivofernandes**

### CODE REVIEW

**Comment by sjmcdowall** [comment]
@ivofernandes -- any chance you can add a test to make sure we don't get a regression in the future on this?

**Comment by felipecastrosales** [comment]
that would be really good, @sjmcdowall.

**Review by felipecastrosales — COMMENTED** [review]
@ivofernandes, [as I mentioned](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/459#issuecomment-1435124079), your branch solved my problem.

**Comment by sjmcdowall** [comment]
That's good to know it will fix the issue @felipecastrosales ... I will merge in a bit -- still hoping to get a test added :)

**Comment by felipecastrosales** [comment]
perfect. thank you very much, @sjmcdowall and @ivofernandes. :)

**Comment by ivofernandes** [comment]
Just added the decoration and the controller to the main example of the app :) 

So next time that the project is not exporting the needed classes the example will not work

**Comment by ivofernandes** [comment]
I'm also not sure that the example app should start with the cupertino type ahead stuff on iOS, but now the example app have a button to switch between material and cupertino

**Pull request merged**
