### PR TITLE
fix not showing suggestions when focused again

### PR DESCRIPTION
**Pull request by rockingdice**
This should partially fix issue #133.

But the animation is not quite right. Need tweaks.

### CODE REVIEW

**Comment by KaYBlitZ** [comment]
Do you remember the exact steps to replicate this?

**Comment by rockingdice** [comment]
It should be easy to repro. After losing the focus of this widget, tap again and the suggestion is not shown. The users may expect a suggestion if there are keywords.

**Comment by thomasschwarzott** [comment]
@AbdulRahmanAlHamali @KaYBlitZ can you please merge this pull request? It really solves an existing bug in our app! :-)

**Comment by blinkn** [comment]
Need this PR, can someone accept?

**Comment by gustav3d** [comment]
Myself has been forced to fork this library :(  I truly hope its a temporary solution.

**Comment by sjmcdowall** [comment]
LGTM

**Comment by Joluall** [comment]
Well I was having trouble whe refocus the textfield afther the onSuggestionSelected event, so, I fixed by waiting milisecons to give focus to the textfield again:

`Future.delayed(const Duration(milliseconds: 50), () {
        nameFocusNode.requestFocus();
      });`

**Pull request merged**
