### PR TITLE
Fix for #23

### PR DESCRIPTION
**Pull request by kika**
The fix for #23, the state of the widget was created untyped.

### CODE REVIEW

**Comment by KaYBlitZ** [comment]
I tested your changes and it fixed the entire screen crash, but the suggestions list box was red (errored). I added in some more missing generic types in a PR request in your repository. Those fixed all errors for me. If you can test and merge those fixes, I think we are good....

**Comment by AbdulRahmanAlHamali** [comment]
@KaYBlitZ, @sjmcdowall 
Alright I merged this along with a few fixes to README, I think we can add to them the `hideOnLoading`, `hideOnError` and `hideOnEmpty` properties, and release 0.7.0.

Btw I think we should release a version 1 by now. Shouldn't we? :smiley:

**Comment by sjmcdowall** [comment]
BTW -- I added Kenneth to the uploaders (or did an add) -- you just need to accept Kenneth. :)

**Comment by KaYBlitZ** [comment]
Thanks a bunch. I just accepted.

**Pull request merged**
